### ISSUE TITLE
over 15min voice call 

### ISSUE THREAD

**Issue by kwangjaeyoo** [VoiSmart/pjsip-android#99]
15 minutes after starting the call,

There is no sound.

using other lib will just hang up,

pjsip is not cut off and there is no sound.

**Comment by aenonGit** [comment]
What's the issue here? Why after 15m there is no sound? Server stuff? And why should the call be closed?

**Comment by kwangjaeyoo** [comment]
Call normally until 15 minutes. 

After 15 min Call no Sound.

(other sip lib call after 15 call is normal.)

Is the time set session connection period???

**Comment by aenonGit** [comment]
You said: `using other lib will just hang up` then you said again: `other sip lib call after 15 call is normal`. I don't get it. But putting everything aside, your problem is that after 15m you won't get any sound? On which end? Caller? Receiver? Which one is using pjsip? Have you traced the sip/RTP traffic? What happens? Both side do not receive any sound or just one?

**Comment by kwangjaeyoo** [comment]
both pjsip and after 15 min NO Sound both 

one Pjsip / other lib 
after 15min : pjsip NO Sound / other lib hang up ( i don't know why hang up call)

both other lib is  normally call after 15 min

Sorry for wrong english~

**Comment by kwangjaeyoo** [comment]
It seems to be a problem with my server.

sip lib works fine.

Thank you.
